name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - name: Linux-x86_64
          os: ubuntu-latest
        - name: macOS-aarch64
          os: macos-latest
        - name: macOS-x86_64
          os: macos-13
    steps:
    - name: Install Elan
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build lean-smt
      run: |
        lake update
        lake build Smt Smt.Rat Smt.Real
    - name: Test lean-smt
      run: lake test
